### ISSUE TITLE
Setup Woes

### ISSUE THREAD

**Issue by slacksystem** [Zephiles/TTYD-Practice-Codes#10]
I'm setting this up again after a while, and I'm having what at first seemed to be the same issue as in #5, where I hacked my save using the tool linked in the user doc loading that file and the practice codes from the release in the memory, then running the game, selecting the save file, it resets, the select the same file again, it resets again, and again and again, never actually loading the save. I created a new issue though because I tried the [solution](https://github.com/Zephiles/TTYD-Practice-Codes/issues/5#issuecomment-1002266214) @Dovahkiin191 suggested in that issue, adding the gecko codes, (which I've since triple-checked), but while that seems to have solved it for me last time, I'm still resetting every time I try to load the save, and in the process I'm seeing nothing indicating anything related to the practice code, aside from the fact that the hack renamed my save to REL Loader.

**Comment by slacksystem** [comment]
Trying with a new save gci from the other link in the user guide works. I wasn't that far in and it seems among all of the file copying and trying things, I lost my save anyway. Might be worth trying to figure out the problem anyway though

**Comment by slacksystem** [comment]
Oops looks like I spoke too soon. I had gotten to the title screen, and it said practice codes and stuff on it like it had loaded the codes, and I could open the menu with L + Start, but when I tried to load the save it would always reboot again. So, progress, but still can't actually play

**Comment by Zephiles** [comment]
The `REL Loader` file is intended to be loaded exactly once, which applies the code that loads the REL at boot. After this, you use the other two saves as normal, and the `REL Loader` file does not need to be used again.

**Comment by slacksystem** [comment]
Thank you. I think it would help to mention in the user manual that the number of the save you pick on the hack webpage should *not* be the number that contains your active save file. It has the potential (as we've seen) to be very confusing otherwise. I selected the number that contained the save file I wanted to keep, thinking that since we're hacking our save file we should say which save we're using. So the issue I was having was that the webpage overwrote my save with the REL Loader save, so I thought I must be supposed to use that file going forward. A sentence explaining that part of the site could help save the next person (and potentially you if they also ask for help) a lot of trouble. Cheers.
