### ISSUE TITLE
_OS_Error_ISI

### ISSUE THREAD

**Issue by pennington20** [Zephiles/TTYD-Practice-Codes#2]
I have been trying to get the practice codes to run and am stuck. I used the hacked save file. When I load the loader save file it does the soft reset as you describe and when the game relaunches I see the practice file message about how to access the menu. I launch a save file and it runs from the beginning like normal. During the sequence with Mario and luigi I verified that the menu operates normally. Then we get to the title screen, with the title hovering over the boat and ocean. Right after moving through that screen the screen goes white and I get a warning box that says: Unknown Pointer 0x03384d40 PC 0x802ba338 LR 0x80005aec. I can click out of the box and continue the game. It will load the prologue curtain call like normal. After that, the screen goes dark. You here Mario snore once, see a text box start to open, and then the screen goes black and the text in the screen shots scroll. I have limited programming experience, so I'd appreciate it if you have any idea what is causing the problem. 
![Annotation 2020-09-13 192633](https://user-images.githubusercontent.com/71241839/93039944-b460df80-f5fd-11ea-8fc7-53a0bd2c699c.png)
![Capture1](https://user-images.githubusercontent.com/71241839/93039954-bb87ed80-f5fd-11ea-9e0f-7788a2c4c0f5.PNG)
Thanks and thanks for creating these tools

**Comment by Zephiles** [comment]
This crash doesn't occur for me, so I need more details.

What version of the Practice Codes are you using?
What version of Dolphin are you using?
Are you able to replicate this crash consistently?

**Comment by Zephiles** [comment]
Seeing as there hasn't been a response in a long time, I will be closing this issue.
