### ISSUE TITLE
Practice Codes w/ other mods

### ISSUE THREAD

**Issue by 8bitendo** [Zephiles/TTYD-Practice-Codes#3]
Hi there!

Is there any way to use these Practice Codes with jdaster64's shufflizer? 

In addition, is that possible to inject codes directly by modifying ISO file?

Thanks!

Best regards.

**Comment by Zephiles** [comment]
The Practice Codes and Shufflizer projects are not compatible in any way.

It is possible to inject codes directly by modifying an ISO file, but that has nothing to do with this project.
