### ISSUE TITLE
Game Crashes When I Start A File

### ISSUE THREAD

**Issue by bruhaps** [Zephiles/TTYD-Practice-Codes#4]
I've followed the directions in the manual, but when I start a file after the soft reset, the game just crashes.

What happens is that I go to the REL save file, and after the reset I go to my file. Then Dolphin shows this message.
![error1](https://user-images.githubusercontent.com/68791868/121949250-1a090600-cd0d-11eb-80d7-a007279ce61f.png)

Then a similar error appears after I press ok.
![error2](https://user-images.githubusercontent.com/68791868/121949584-79ffac80-cd0d-11eb-8ec2-58bf2883455d.png)

Finally, the game switches to a crash screen and a final error message appears.
![error3](https://user-images.githubusercontent.com/68791868/121949865-d662cc00-cd0d-11eb-9def-cfd17e754ebb.png)
![errorscreen](https://user-images.githubusercontent.com/68791868/121949885-dbc01680-cd0d-11eb-8fad-81e4a561eaa1.png)
![errorscreen2](https://user-images.githubusercontent.com/68791868/121949899-dfec3400-cd0d-11eb-9830-29b0b0491f40.png)
![errorscreen3](https://user-images.githubusercontent.com/68791868/121949914-e2e72480-cd0d-11eb-9cff-3c0ed95176df.png)

Once I press No, Dolphin just hard crashes.

**Comment by Zephiles** [comment]
There's a number of possible reasons for this occuring, but the two most likely reasons are as follows:

1. It's a bug with Dolphin 5.0. The 5.0 stable release that you're using is extremely outdated and buggy. You should instead use a newer dev build.
2. You may have some other cheats active (Action Replay and/or Gecko) that are incompatible with this mod.

Deal with these two points, and then report if the crash still occurs.

**Comment by bruhaps** [comment]
I updated Dolphin, disabled the action codes and the game works! thanks!
