### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by slacksystem** [Zephiles/TTYD-Practice-Codes#5]
Hi I'm trying to get this setup. I have the European version of the game. I started by trying with Dolphin Version 5.0-15445.  I loaded the file G8ME_rel_PracticeCodes.gci onto my memory card. I used the tool you linked in your user guide to hack my save file. I started the game and selected the REL Loader save file. The game soft reset as expected but continued to do that each time I selected my save. I then decided to try with the empty hacked file TTYD_EU_REL_Loader.gci from this site. I get the same issue. I tried updating to dolphin version 5.0-15661 but no change. Is there something I'm doing wrong? I'm not using any other codes and it's the normal version of the ROM.

**Comment by Dovahkiin191** [comment]
No thanks to the ignorant creator of the practice codes, youll need to first import the practice codes.gci from the memcard manager along with the games save, if not already done, then, you need to add a new gecko code into the gecko codes section (it's next to the AR codes section), paste the gecko code into the "codes" section at the bottom, give it a name and save it. I know it's extra work, but It'll then work once you launch the game.

**Comment by slacksystem** [comment]
Is it a specific gecko code?

**Comment by Dovahkiin191** [comment]
Click and download "source code" located under assets, open the file, click
"ttyd-practice-codes-3.0.52" or whichever version you're using, click "ttyd
tools" then "relloader-ttyd" then "REL_Loader" then "Gecko" then
REL_Loader_(version you're using)_Gecko.txt, open your versions text
document and copy the codes, NOT the words above, ONLY the numbers. For
example. I used REL_Loader_US_Gecko.txt. hope this helps! Email back if it
doesn't and I'll take you through the steps again to get it working

**Comment by slacksystem** [comment]
Thank you it's working! I appreciate your help ♥

**Comment by Dovahkiin191** [comment]
Anytime! Glad to help🙂
